#!/usr/bin/env node
// words-to-ass.mjs — turn word timings into brand-styled, word-by-word highlighted ASS captions for a 1080x1920 short.
// Usage: node words-to-ass.mjs <words.json> <out.ass> [--max-words 3] [--max-chars 20] [--upper] [--y 1180]
// words.json: [{ "word": "rain", "start": 0.20, "end": 0.48 }, ...]  (seconds; from your TTS/transcription timestamps)
// Node >= 20, no dependencies, no network. Burn with ../short-form-editing/scripts/burn-captions.sh (needs libass).
import { readFileSync, writeFileSync } from "node:fs";

const [, , inPath, outPath, ...rest] = process.argv;
if (!inPath || !outPath) {
  console.error("usage: node words-to-ass.mjs words.json out.ass [--max-words 3] [--max-chars 20] [--upper] [--y 1180]");
  process.exit(2);
}
const opt = (name, def) => { const i = rest.indexOf(name); return i >= 0 && rest[i + 1] ? Number(rest[i + 1]) : def; };
const maxWords = opt("--max-words", 3);
const maxChars = opt("--max-chars", 20);
const y = opt("--y", 1180);              // vertical centre of the caption line, px from the top (inside the safe zone)
const upper = rest.includes("--upper");

// Brand colours as ASS &HAABBGGRR
const INK = "&H00E2E9EC&";   // #ece9e2 off-white
const ROSE = "&H00A56FFF&";  // #ff6fa5 rose (active word)

const words = JSON.parse(readFileSync(inPath, "utf8"));
if (!Array.isArray(words) || !words.every((w) => typeof w.word === "string" && w.end > w.start)) {
  console.error("words.json must be an array of { word, start, end } with end > start");
  process.exit(2);
}

// Group words into short lines: break on max words, max chars, sentence punctuation, or a pause > 0.35 s.
const lines = [];
let cur = [];
for (const w of words) {
  const text = cur.map((c) => c.word).concat(w.word).join(" ");
  const pause = cur.length ? w.start - cur[cur.length - 1].end : 0;
  if (cur.length && (cur.length >= maxWords || text.length > maxChars || pause > 0.35)) { lines.push(cur); cur = []; }
  cur.push(w);
  if (/[.!?]$/.test(w.word)) { lines.push(cur); cur = []; }
}
if (cur.length) lines.push(cur);

const ts = (s) => {
  const cs = Math.max(0, Math.round(s * 100));
  const h = Math.floor(cs / 360000), m = Math.floor((cs % 360000) / 6000), sec = Math.floor((cs % 6000) / 100), c = cs % 100;
  return `${h}:${String(m).padStart(2, "0")}:${String(sec).padStart(2, "0")}.${String(c).padStart(2, "0")}`;
};
const esc = (t) => t.replace(/[{}\\]/g, "");

const events = [];
lines.forEach((line, li) => {
  const nextLineStart = li < lines.length - 1 ? lines[li + 1][0].start : Infinity;
  line.forEach((w, i) => {
    const start = w.start;
    // hold the last word of a line a beat, but never overlap the next line
    const end = i < line.length - 1 ? line[i + 1].start : Math.min(w.end + 0.12, nextLineStart);
    const text = line
      .map((x, j) => {
        const t = esc(upper ? x.word.toUpperCase() : x.word);
        return j === i ? `{\\c${ROSE}}${t}{\\c${INK}}` : t;
      })
      .join(" ");
    // \pos keeps the line at a fixed safe position; a 60 ms pop-in on the first word of each line
    const fx = i === 0 ? "{\\fad(60,0)}" : "";
    events.push(`Dialogue: 0,${ts(start)},${ts(end)},Word,,0,0,0,,{\\an5\\pos(540,${y})}${fx}${text}`);
  });
});

const header = `[Script Info]
; Claudia word-by-word captions — generated by words-to-ass.mjs
ScriptType: v4.00+
PlayResX: 1080
PlayResY: 1920
WrapStyle: 2
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Word,Barlow Condensed ExtraBold,76,${INK},${INK},&H000D0B0A&,&H990D0B0A&,0,0,0,0,100,100,0,0,1,4,0,5,90,120,0,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;
writeFileSync(outPath, header + events.join("\n") + "\n");
console.log(`wrote ${events.length} events in ${lines.length} lines → ${outPath}`);
