#!/usr/bin/env node
// Builds the library: index.json, dist/skills/<slug>.zip, dist/claudia-skills-all.zip and the skill tables in README.md.
// Node >= 20, no dependencies. Output is deterministic (same files → same bytes → same sha256).
//
//   node scripts/build.mjs                 validate, then build (exit 1 if any skill has errors)
//   --allow-invalid    build even when validation fails (prints the report; use while skills are still being written)
//   --root <dir>       build another checkout (a folder that contains skills/); writes into that folder
//   --quiet            only print the summary line
//
// Each zip holds the skill folder at its root (<slug>/SKILL.md, <slug>/templates/…), so unzipping into a skills
// directory (~/.claude/skills, ~/.agents/skills, …) installs it, and claude.ai accepts it as an upload.
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { CATEGORIES, findSkillDirs, listFiles, readSkill, relatedSlugs, splitList } from "./lib/skills.mjs";
import { createZip } from "./lib/zip.mjs";
import { printReport, validateAll } from "./validate.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = resolve(HERE, "..");
export const INDEX_VERSION = 1;
export const ALL_ZIP = "claudia-skills-all.zip";
const README_START = "<!-- skills:start (generated by scripts/build.mjs — edit the skills, not this table) -->";
const README_END = "<!-- skills:end -->";

const sha256 = (buf) => createHash("sha256").update(buf).digest("hex");
const dateOf = (ymd) => (/^\d{4}-\d{2}-\d{2}$/.test(ymd ?? "") ? new Date(`${ymd}T00:00:00Z`) : new Date(Date.UTC(2026, 0, 1)));

/**
 * Builds everything in memory. Returns { index, zips: Map<fileName, Buffer>, readme: string|null, report }.
 * Nothing is written unless write() is called on the result.
 */
export function build(root = REPO_ROOT, { allowInvalid = false } = {}) {
  const report = validateAll(root);
  const failing = new Set(report.results.filter((r) => r.errors.length).map((r) => r.slug));
  if (failing.size && !allowInvalid) return { ok: false, report };

  const skills = [];
  const zips = new Map();
  const allEntries = [];
  for (const d of findSkillDirs(root)) {
    if (!existsSync(join(d.dir, "SKILL.md"))) continue;
    const s = readSkill(d.dir);
    const m = s.metadata;
    const files = listFiles(d.dir).filter((f) => !f.symlink);
    const entries = files.map((f) => ({ name: `${d.slug}/${f.path}`, data: readFileSync(join(d.dir, f.path)), mode: f.mode & 0o111 ? 0o755 : 0o644 }));
    const zip = createZip(entries, { date: dateOf(m.updated) });
    zips.set(`${d.slug}.zip`, zip);
    allEntries.push(...entries);
    skills.push({
      slug: d.slug,
      name: s.fields.name ?? d.slug,
      title: m.title ?? d.slug,
      category: d.category,
      summary: m.summary ?? "",
      description: (s.fields.description ?? "").trim(),
      level: m.level ?? "",
      tags: splitList(m.tags),
      uses: splitList(m.uses),
      time: m.time ?? "",
      version: m.version ?? "",
      updated: m.updated ?? "",
      files: files.map((f) => f.path),
      size: files.reduce((n, f) => n + f.size, 0),
      bytes: zip.length,
      sha256: sha256(zip),
      path: `skills/${d.category}/${d.slug}`,
      zip: `/skills/${d.slug}.zip`,
      related: relatedSlugs(s.body).filter((x) => x !== d.slug),
      valid: !failing.has(d.slug),
    });
  }
  const order = new Map(CATEGORIES.map((c, i) => [c.id, i]));
  skills.sort((a, b) => (order.get(a.category) ?? 9) - (order.get(b.category) ?? 9) || 0);
  const updated = skills.reduce((max, s) => (s.updated > max ? s.updated : max), "");
  const all = createZip(allEntries, { date: dateOf(updated) });
  zips.set(ALL_ZIP, all);
  const index = {
    version: INDEX_VERSION,
    updated: updated || null,
    count: skills.length,
    repo: "https://github.com/claudia-onchain/claudia-skills",
    all: { zip: `/skills/${ALL_ZIP}`, bytes: all.length, sha256: sha256(all) },
    categories: CATEGORIES.map((c) => ({ ...c, count: skills.filter((s) => s.category === c.id).length })),
    skills,
  };

  const readmePath = join(root, "README.md");
  let readme = null;
  if (existsSync(readmePath)) {
    const cur = readFileSync(readmePath, "utf8");
    const a = cur.indexOf(README_START);
    const b = cur.indexOf(README_END);
    if (a !== -1 && b > a) readme = `${cur.slice(0, a)}${README_START}\n${readmeTables(index)}\n${cur.slice(b)}`;
  }
  const built = new Set(skills.map((x) => x.slug));
  const skipped = [...failing].filter((x) => !built.has(x));
  return { ok: true, report, index, zips, readme, failing: new Set([...failing].filter((x) => built.has(x))), skipped };
}

const cell = (s) => String(s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");

export function readmeTables(index) {
  const out = [];
  out.push(`${index.count} skills${index.updated ? ` · updated ${index.updated}` : ""} · [download all (zip)](https://useclaudia.xyz/skills/${ALL_ZIP})`);
  for (const c of index.categories) {
    const rows = index.skills.filter((s) => s.category === c.id);
    out.push("", `### ${c.title} · ${rows.length}`, "", c.summary, "");
    if (!rows.length) {
      out.push("_Coming soon._");
      continue;
    }
    out.push("| Skill | What it does | Level | Time |", "| --- | --- | --- | --- |");
    for (const s of rows) out.push(`| [${cell(s.title)}](${s.path}/SKILL.md) | ${cell(s.summary)} | ${cell(s.level)} | ${cell(s.time)} |`);
  }
  return out.join("\n");
}

/** Writes index.json, dist/ and README.md for a successful build. */
export function write(root, result) {
  writeFileSync(join(root, "index.json"), `${JSON.stringify(result.index, null, 2)}\n`);
  const dist = join(root, "dist");
  const skillsDist = join(dist, "skills");
  mkdirSync(skillsDist, { recursive: true });
  const want = new Set();
  for (const [name, buf] of result.zips) {
    if (name === ALL_ZIP) writeFileSync(join(dist, name), buf);
    else {
      want.add(name);
      writeFileSync(join(skillsDist, name), buf);
    }
  }
  for (const f of readdirSync(skillsDist)) if (!want.has(f)) rmSync(join(skillsDist, f), { force: true });
  if (result.readme !== null) writeFileSync(join(root, "README.md"), result.readme);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  const rootIdx = args.indexOf("--root");
  const root = rootIdx >= 0 ? resolve(args[rootIdx + 1]) : REPO_ROOT;
  const quiet = args.includes("--quiet");
  const result = build(root, { allowInvalid: args.includes("--allow-invalid") });
  if (!quiet || !result.ok) printReport(result.report);
  if (!result.ok) {
    console.error("\nBuild stopped: fix the errors above (or pass --allow-invalid while skills are still being written).");
    process.exit(1);
  }
  write(root, result);
  const kb = (n) => `${(n / 1024).toFixed(1)} KB`;
  console.log(`\nBuilt ${result.index.count} skills → index.json, dist/skills/*.zip, dist/${ALL_ZIP} (${kb(result.index.all.bytes)})${result.readme !== null ? ", README tables" : " (README markers not found — tables skipped)"}`);
  if (result.failing.size) console.log(`Built with --allow-invalid: ${result.failing.size} skill(s) still have errors: ${[...result.failing].join(", ")}`);
  if (result.skipped.length) console.log(`Skipped (no SKILL.md yet): ${result.skipped.join(", ")}`);
}
